---
- name: View AWS machines
  hosts: all
  connection: local
  gather_facts: False
  tasks:
   - ec2_instance_facts:
       profile: ansible-book
       region: eu-central-1
       filters:
         "instance-state-name": running
     register: instance_list
   - debug: var=instance_list