---
- hosts: all
  become: true
  tasks:
    # PHP
    - name: Add the ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php'
    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Install PHP
      apt: name={{item}} state=installed
      with_items:
        - php7.1
        - php7.1-fpm
        - php7.1-mysql
        - php7.1-xml
    - name: Remove apache2
      apt: name=apache2 state=removed
    # MySQL
    - name: Install MySQL
      apt: name={{item}} state=installed
      with_items:
        - mysql-server-5.6
        - python-mysqldb
    - name: Generate new root password
      command: openssl rand -hex 7 creates=/root/.my.cnf
      register: mysql_new_root_pass
    - name: Remove anonymous users
      mysql_user: name="" state=absent
    - name: Remove test database
      mysql_db: name=test state=absent
    - name: Update root password
      mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_pass.changed
    - name: Create my.cnf
      template: src=templates/mysql/my.cnf dest=/root/.my.cnf
      when: mysql_new_root_pass.changed
    - name: Output new root password
      debug: msg="New root password is {{mysql_new_root_pass.stdout}}"
      when: mysql_new_root_pass.changed
    # Nginx
    - name: Install nginx
      apt: name=nginx state=installed
    - name: Start nginx
      service: name=nginx state=started
    - name: Create nginx config
      template: src=templates/nginx/default dest=/etc/nginx/sites-available/default
      notify: restart nginx
    # Wordpress
    - name: Get WordPress checksum
      uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
      register: wp_checksum
    - name: Download WordPress
      get_url:
        url=https://wordpress.org/latest.zip
        dest=/tmp/wordpress.zip
        checksum="sha1:{{wp_checksum.content}}"
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted