---
- hosts: all
  become: true
  tasks:
    - name: Install NMP
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - nginx
        - mysql-server-5.6
        - php5-cli